TYPE = GENERIC STRING
OPENAI_API_KEY = "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"

